# Generated by Django 6.1 on 2026-09-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_business_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_document',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_document_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_submitted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin_submitted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nin_verified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified_at',
        ),
    ]
