# Generated by Django 6.1 on 2026-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller'), ('bank', 'Bank'), ('realestate', 'Real Estate Company')], default='customer', max_length=20),
        ),
    ]
