# Generated by Django 6.1 on 2026-09-08 20:55

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Real Estate',
                'verbose_name_plural': 'Real Estates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.managers.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Pokea updates za applications kwa email'),
        ),
    ]
