# Generated by Django 6.1 on 2026-09-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_bankproxy_realestateproxy_user_notify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly interest rate in PERCENT (e.g. 12.50 means 12.5% p.a. - this is NOT the fee)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='One-time processing fee as TZS AMOUNT (e.g. 500000 - fill this so applicants see it instead of —)', max_digits=15, null=True),
        ),
    ]
