# Generated by Django 6.1 on 2026-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_interest_rate_alter_user_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, help_text='Mteja alisoma notifications lini mwisho (badge ya kengele)', null=True),
        ),
    ]
