# Generated by Django 6.1 on 2026-09-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_notifications_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_repayment_period',
            field=models.IntegerField(blank=True, help_text='Maximum repayment period in MONTHS (e.g. 180 for 15 years - NMB max 180)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Processing fee in PERCENT (e.g. 1.00 means 1% - applicants see 1%)', max_digits=5, null=True),
        ),
    ]
