# Generated by Django 6.1 on 2026-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_bank_max_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the verification email was last sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, default='', help_text='One-time token sent by email', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email address has been verified via verification link'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the email was verified', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_requirements',
            field=models.TextField(blank=True, help_text='Bank requirements (comma separated)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications_seen_at',
            field=models.DateTimeField(blank=True, help_text='When the user last read notifications (bell badge)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Receive application updates via email'),
        ),
    ]
