# Generated by Django 6.1 on 2026-09-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_create_google_social_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_selection_pending',
            field=models.BooleanField(default=False, help_text='New social user still needs to select customer/realestate role'),
        ),
    ]
