# Generated by Django 6.1 on 2026-08-24 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('area', models.DecimalField(decimal_places=2, help_text='Eneo katika mita za mraba', max_digits=10)),
                ('property_type', models.CharField(choices=[('house', 'Nyumba'), ('apartment', 'Ghorofa'), ('land', 'Ardhi'), ('commercial', 'Biashara')], default='house', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Inapatikana'), ('sold', 'Imeuzwa'), ('rented', 'Imekodishwa'), ('pending', 'Inasubiri')], default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role__in': ['seller', 'realestate']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
