# Generated by Django 6.1 on 2026-09-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='napa',
            field=models.CharField(blank=True, help_text='NaPa - Namba ya hati / kumbukumbu ya kiwanja (kama ipo)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image - itaonekana kwa bank na customers', null=True, upload_to='properties/'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('is_cover', models.BooleanField(default=False, help_text='Picha ya cover itakayoonekana kwa bank na customers')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='properties.property')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
