# Generated by Django 6.1 on 2026-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_napa_alter_property_id_alter_property_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='backup_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='building_permit_file',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/building_permit/'),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, help_text='Floor number (for apartment)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('partially', 'Partially')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='infrastructure_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='infrastructure_fenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='infrastructure_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='infrastructure_road',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='infrastructure_sewage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='infrastructure_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='land_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/land_certificate/'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Land size sqm (for house)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('mixed', 'Mixed Use')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='land_use',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('mixed', 'Mixed Use')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.IntegerField(default=0, help_text='Number of parking spaces'),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_dimensions',
            field=models.CharField(blank=True, help_text='e.g. 20m x 25m', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.CharField(choices=[('house', 'House'), ('plot', 'Plot')], default='house', help_text='House or Plot', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('needs_renovation', 'Needs Renovation'), ('under_construction', 'Under Construction')], max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='property_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='House size sqm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='survey_plan_available',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='survey_plan_file',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/survey_plan/'),
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='tax_clearance_file',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/tax_clearance/'),
        ),
        migrations.AddField(
            model_name='property',
            name='title_deed_available',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('in_process', 'In Process')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='title_deed_file',
            field=models.FileField(blank=True, null=True, upload_to='properties/documents/title_deed/'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, help_text='Total floors in building', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning',
            field=models.CharField(blank=True, choices=[('residential', 'Residential Zone'), ('commercial', 'Commercial Zone'), ('industrial', 'Industrial Zone'), ('agricultural', 'Agricultural Zone')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='Area in square meters', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image - visible to banks and customers', null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='napa',
            field=models.CharField(blank=True, help_text='Plot/Title No. - plot reference number (if available)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('land', 'Land'), ('commercial', 'Commercial')], default='house', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending'), ('reserved', 'Reserved'), ('under_construction', 'Under Construction')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Cover image visible to banks and customers'),
        ),
    ]
