# Generated by Django 6.1 on 2026-09-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_add_house_plot_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('applied', 'Applied'), ('verifying', 'Bank Verifying'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending'), ('reserved', 'Reserved'), ('under_construction', 'Under Construction')], default='available', max_length=20),
        ),
    ]
