# Generated by Django 6.1 on 2026-09-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-deleted by seller - hidden from customers'),
        ),
    ]
