# Generated by Django 6.1 on 2026-08-24 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('repayment_period', models.IntegerField(help_text='Muda wa marejesho kwa miezi')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('document_verification', 'Ukaguzi wa Nyaraka'), ('valuation', 'Tathmini ya Nyumba'), ('credit_assessment', 'Tathmini ya Mikopo'), ('approved', 'Imeidhinishwa'), ('rejected', 'Imekataliwa'), ('disbursed', 'Fedha Zimetolewa')], default='pending', max_length=30)),
                ('affordability_score', models.FloatField(blank=True, help_text='Alama ya uwezo wa kulipa (0-100)', null=True)),
                ('risk_score', models.FloatField(blank=True, help_text='Alama ya hatari (0-100, juu = hatari kubwa)', null=True)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dti_ratio', models.FloatField(blank=True, help_text='Debt-to-Income Ratio', null=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='mortgage_documents/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_applications', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_applications', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_remaining', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('paid', 'Imelipwa'), ('overdue', 'Imechelewa')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='mortgages.mortgageapplication')),
            ],
        ),
    ]
