# Generated by Django 6.1 on 2026-08-31 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgageapplication',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('business_owner', 'Business Owner'), ('business', 'Business Owner'), ('unemployed', 'Unemployed')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MortgageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mortgage_documents/')),
                ('doc_type', models.CharField(choices=[('id_passport', 'ID/Passport Copy'), ('payslip', 'Pay Slip'), ('bank_statement', 'Bank Statement'), ('tax_clearance', 'Tax Clearance'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_files', to='mortgages.mortgageapplication')),
            ],
        ),
    ]
