# Generated by Django 6.1 on 2026-09-02 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0002_mortgage_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageapplication',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Bank iliyochaguliwa na customer (Hatua 6)', limit_choices_to={'role': 'bank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_mortgages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mortgagedocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
