# Generated by Django 6.1 on 2026-09-07 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0003_mortgageapplication_bank_and_more'),
        ('properties', '0003_add_house_plot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mortgageapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='current_step',
            field=models.IntegerField(default=1, help_text='Wizard step where user saved - 1..8'),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full form draft for resume'),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('refinance', 'Refinance/Equity Release'), ('semi_finish', 'Semi Finish'), ('construction', 'Construction'), ('land', 'Land Purchase'), ('commercial', 'Commercial')], help_text='Type of loan - purchase/construction etc', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='mortgage_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('construction', 'Home Construction'), ('renovation', 'Renovation'), ('land', 'Land Purchase'), ('commercial', 'Commercial')], help_text='Mortgage category from ?type= param', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='affordability_score',
            field=models.FloatField(blank=True, help_text='Affordability score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Bank selected by customer', limit_choices_to={'role': 'bank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_mortgages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='monthly_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_applications', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='repayment_period',
            field=models.IntegerField(blank=True, help_text='Repayment period in months', null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='Risk score (0-100, higher = higher risk)', null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Incomplete'), ('pending', 'Pending'), ('document_verification', 'Document Verification'), ('valuation', 'Valuation'), ('credit_assessment', 'Credit Assessment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
