# Generated by Django 6.1 on 2026-09-09 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0004_draft_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageapplication',
            name='review_note',
            field=models.TextField(blank=True, help_text='Latest bank note shown to customer', null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='review_stage',
            field=models.CharField(default='received', help_text='Current bank review stage', max_length=30),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft - Incomplete'), ('pending', 'Pending'), ('document_verification', 'Document Verification'), ('crb_check', 'CRB Check'), ('valuation', 'Valuation'), ('credit_assessment', 'Credit Assessment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicationTimelineEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('received', 'Received by Bank'), ('document_verification', 'Document Verification'), ('crb_check', 'CRB / Credit Reference Check'), ('valuation', 'Property Valuation'), ('credit_assessment', 'Credit Assessment'), ('approval_decision', 'Approval Decision'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('note', 'General Update')], default='received', max_length=30)),
                ('title', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='mortgages.mortgageapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
