# Generated by Django 6.1 on 2026-09-09 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0005_mortgageapplication_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Document re-upload'), ('nida', 'NIDA / ID number'), ('info', 'Information / text'), ('other', 'Other')], default='document', max_length=20)),
                ('target', models.CharField(blank=True, default='', help_text="Which document/field, e.g. 'hati', 'NIDA'", max_length=200)),
                ('instructions', models.TextField(help_text='Bank instructions shown to the customer')),
                ('status', models.CharField(choices=[('pending', 'Pending customer action'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('response_text', models.TextField(blank=True, default='')),
                ('response_file', models.FileField(blank=True, null=True, upload_to='correction_responses/')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='mortgages.mortgageapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
