# Generated by Django 6.1 on 2026-09-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0007_banknotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageapplication',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average annual income for business owner', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='BRELA BRL-... or Halmashauri LIC-... number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='business_type',
            field=models.CharField(blank=True, choices=[('wholesale', 'Wholesale'), ('retail', 'Retail')], help_text='Wholesale or Retail only', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='dob',
            field=models.DateField(blank=True, help_text='Birth date - must be 18-57 years, must match NIDA', null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], help_text='Single or Married', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='marriage_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='mortgage_documents/marriage/'),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='marriage_certificate_number',
            field=models.CharField(blank=True, help_text='Marriage certificate card number (if married)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='nida_number',
            field=models.CharField(blank=True, help_text='NIDA number 20 digits - first 8 encode DOB YYYYMMDD', max_length=30, null=True),
        ),
    ]
