# Generated by Django 6.1 on 2026-09-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgages', '0009_add_deductions_and_other_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgageapplication',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name at the selected bank', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Customer account number at the selected bank', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='business_years',
            field=models.IntegerField(blank=True, help_text='Years in business', null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('contract', 'Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='dependents',
            field=models.IntegerField(blank=True, default=0, help_text='Number of dependents', null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mortgageapplication',
            name='years_employed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='deduction_heslb',
            field=models.BooleanField(default=False, help_text='HESLB 15% of salary - for those with education loan'),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='deduction_paye',
            field=models.BooleanField(default=False, help_text='PAYE 0-30% based on income bracket'),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='deduction_psssf',
            field=models.BooleanField(default=False, help_text='PSSSF 5% of salary - public sector employees only'),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='employment_sector',
            field=models.CharField(blank=True, choices=[('public', 'Public Sector'), ('private', 'Private Sector')], help_text='Public vs Private sector - PSSSF 5% applies only to public', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='has_other_loan',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Do you have another loan at a different bank?', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='net_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net monthly income after deductions', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='other_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount of existing loan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='other_loan_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding balance', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='other_loan_bank',
            field=models.CharField(blank=True, help_text='Existing loan bank name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='other_loan_consolidate',
            field=models.CharField(blank=True, choices=[('yes', 'Yes - Consolidate'), ('no', 'No - Keep Separate')], help_text='Should the new loan consolidate the old debt? (Takeover)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='other_loan_monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly payment of existing loan', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortgageapplication',
            name='total_deductions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total deductions', max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='MortgageHousePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mortgage_houses/')),
                ('is_cover', models.BooleanField(default=False, help_text='Cover photo shown to the bank')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_photos', to='mortgages.mortgageapplication')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
