# Generated by Django 6.1 on 2026-08-24 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mortgages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('draft', 'Rasimu'), ('pending_signature', 'Inasubiri Kusainiwa'), ('signed', 'Imesainiwa'), ('executed', 'Imetekelezwa')], default='draft', max_length=30)),
                ('customer_signed', models.BooleanField(default=False)),
                ('seller_signed', models.BooleanField(default=False)),
                ('bank_signed', models.BooleanField(default=False)),
                ('lawyer_signed', models.BooleanField(default=False)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('executed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(limit_choices_to={'role': 'bank'}, on_delete=django.db.models.deletion.CASCADE, related_name='bank_contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contracts', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ForeignKey(limit_choices_to={'role': 'lawyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_contracts', to=settings.AUTH_USER_MODEL)),
                ('mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='mortgages.mortgageapplication')),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('mortgage_disbursement', 'Malipo ya Mkopo'), ('installment', 'Marejesho'), ('legal_fee', 'Ada ya Wakili')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('completed', 'Imekamilika'), ('failed', 'Imeshindwa')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.contract')),
            ],
        ),
    ]
