# Generated by Django 6.1 on 2026-09-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='lawyer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='lawyer_signed',
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('executed', 'Executed')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('mortgage_disbursement', 'Mortgage Disbursement'), ('installment', 'Installment'), ('legal_fee', 'Legal Fee')], max_length=30),
        ),
    ]
