# Generated by Django 6.1 on 2026-09-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_contract_lawyer_remove_contract_lawyer_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='physical_signing_date',
            field=models.DateField(blank=True, help_text='Date agreed by the bank for physical signing', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='physical_signing_location',
            field=models.CharField(blank=True, default='', help_text='Location agreed by the bank for physical signing', max_length=255),
        ),
    ]
