# Generated by Django 6.1 on 2026-09-29 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_contract_physical_signing_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'role__in': ['seller', 'realestate']}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
