# Generated by Django 6.0.3 on 2026-09-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_contract_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Bank has published this contract to seller/real estate and buyer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_contract_file',
            field=models.FileField(blank=True, help_text='Final scanned/executed signed contract PDF', null=True, upload_to='contracts/signed/'),
        ),
    ]
